### ISSUE TITLE
Have the backend copy subject to topic on read and write

### ISSUE THREAD

**Issue by emillind** [emillind/zulip#6]
Whenever a request is sent, if it adds a new message with a subject, copy it to provide topic as well. On reading messages have the backend serve up topic as a copy of what subject is. 

When this is done the front end can begin to see the changes required.

**Comment by emillind** [comment]
Having the send message write a topic field in the backend seems to be pretty difficult and i will hold with that. Will take refactoring and changes to the backend Django models and database fetching

**Comment by eywoon** [comment]
Good idea. Gonna take a long time to refactor the js files
