### ISSUE TITLE
Change exports.subject to exports.topic

### ISSUE THREAD

**Issue by eywoon** [emillind/zulip#9]
In compose_state.js, there is the export object that many other classes reference. That has the variable subject that needs to be changed to topic.
See [UML](https://drive.google.com/file/d/1PHKKCSQjAl1t8DvzztCnEZxHF5XZn17U/view?usp=sharing)

Many classes will need to be changed (compose_actions.js etc) and it will most probably require many tests to be updated.

**Comment by emillind** [comment]
First change the exports.subject -> exports.topic and then one global search and replace (cmd+shift+f in Sublime of Atom) will of compose_state.subject -> compose_state.topic will do the trick here. @eywoon
